db:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=dorootpasswd
    - MYSQL_USER=cronlog_user
    - MYSQL_PASSWORD=cronlog_passwd
    - MYSQL_DATABASE=cronlog
  ports:
    - "3306:3306"
app:
  image: php:7
  command: php -S 0.0.0.0:8080 /app/index.php
  ports:
    - "8080:8080"
  volumes:
    - .:/app:z
composer:
  image: composer/composer:php7
  command: install
  volumes:
    - .:/app:z
